# Generated by Django 3.2.4 on 2021-09-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_data',
            name='image',
            field=models.ImageField(default='', upload_to='code_grn/images'),
        ),
    ]
